disabled_rules:
  - line_length
  - identifier_name
  - todo
  - trailing_comma
  - function_parameter_count
opt_in_rules:
  - closure_end_indentation
excluded:
  - Carthage
  - Pods
  - vendor
  - SubsClient/Sources/Generated
