name: SubsClient

targets:
    SubsClient:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources: [SubsClient]
        preBuildScripts:
            - path: scripts/lint.sh
              name: "Run Lint"
        postBuildScripts:
            - path: scripts/format.sh
              name: "Run Format"
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: jp.ca21engineer.SubsClient
