name: SubsClient

packages:
    ComposableArchitecture:
      url: https://github.com/pointfreeco/swift-composable-architecture
      from: 0.3.0

targetTemplates:
    Framework:
      platform: iOS
      type: framework
      deploymentTarget: "13.0"
      sources:
        - path: ${target_name}
      settings:
        PRODUCT_BUNDLE_IDENTIFIER: "jp.ca21engineer.SubsClient.${target_name}"
    UnitTest:
      type: bundle.unit-test
      platform: iOS
      sources:
        - path: ${target_name}
      dependencies:
        - target: ${target_name}
        - target: SubsClient

targets:
    Common:
      templates:
        - Framework
      sources:
        - path: ${target_name}
    CommonTests:
      templates:
        - UnitTest
    Components:
      templates:
        - Framework
      sources:
        - path: ${target_name}
    ComponentsTests:
      templates:
        - UnitTest
    Repository:
      templates:
        - Framework
      sources:
        - path: ${target_name}
      dependencies:
        - package: ComposableArchitecture
    SubsClient:
        type: application
        platform: iOS
        deploymentTarget: "13.4"
        sources: [SubsClient]
        preBuildScripts:
            - path: scripts/lint.sh
              name: "Run Lint"
        postBuildScripts:
            - path: scripts/format.sh
              name: "Run Format"
        settings:
            PRODUCT_BUNDLE_IDENTIFIER: jp.ca21engineer.SubsClient
        dependencies:
            - target: Common
            - target: Components
